module.exports = {
  ORDER_STATUS: {
    PENDING: "PENDING",
    IN_PROGRESS: "IN_PROGRESS",
    CONFIRMED: "CONFIRMED",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    RETURNED: "RETURNED",
  },
  USER_ROLES: {
    ADMIN: "ADMIN",
    CLIENT: "CLIENT",
    VENDOR: "VENDOR",
    LIVREUR: "LIVREUR",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
  },
  PAYMENT_METHOD: {
    CASH: "CASH",
    CARD: "CARD",
    BANK_TRANSFER: "BANK_TRANSFER",
    MOBILE_PAYMENT: "MOBILE_PAYMENT",
  },
};
